# Generated by Django 4.1 on 2022-10-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
    ]
