# Generated by Django 4.1 on 2022-11-01 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0003_remove_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysumup',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='dailysumup',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='dailysumup',
            name='kcal',
        ),
        migrations.RemoveField(
            model_name='dailysumup',
            name='protein',
        ),
    ]
